# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7522ac9b802e6ea70010f3f5e93574cda0432bfc668997ab4806600b9b6e1f4d31b9aede8cc1957f55bf060cc88e077440578ad993e47cb601e97100e9a72ce2

test:
  secret_key_base: e690fd11d6121cb6a44291de5e7601aae70cc9159464940e47abec70186bf83e44376944b1cc4f1c1627727c6d92b5b28c11163bbf97dffbabb9baddfd71bba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
